# Generated by Django 4.1.5 on 2023-01-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.CreateModel(
            name='Diameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('total', models.FloatField(blank=True, default=0, verbose_name='Тотал (не изменяемое поле)')),
            ],
            options={
                'verbose_name': 'Диаметр коронки',
                'verbose_name_plural': 'Диаметры коронок',
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цены материлов',
                'verbose_name_plural': 'Цена метриала',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materialprice')),
            ],
            options={
                'verbose_name': 'Материалы',
                'verbose_name_plural': 'Материал',
            },
        ),
    ]
