# Generated by Django 4.1.5 on 2023-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diameters',
            name='total',
            field=models.FloatField(blank=True, default=0, verbose_name='Тотал (не изменяемое поле)'),
        ),
    ]
