# Generated by Django 4.1.5 on 2023-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные'),
        ),
    ]
