# Generated by Django 4.1.5 on 2023-01-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='diameters',
            name='materials',
            field=models.ManyToManyField(to='api.materials'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
