# Generated by Django 4.1.5 on 2023-02-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Доп работа',
                'verbose_name_plural': 'Доп работы',
            },
        ),
    ]
