# Generated by Django 4.1.5 on 2023-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diameters_materials_alter_materials_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diameters',
            name='materials',
        ),
        migrations.AddField(
            model_name='diameters',
            name='materials',
            field=models.JSONField(blank=True, null=True, verbose_name='Материалы'),
        ),
    ]
