# Generated by Django 4.1.5 on 2023-01-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_diameters_materials_diameters_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, null=True, verbose_name='Материалы')),
            ],
            options={
                'verbose_name': 'JSON',
                'verbose_name_plural': 'JSON',
            },
        ),
    ]
