# Generated by Django 4.1.5 on 2023-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_starttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttotal',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Начальная цена'),
        ),
    ]
