# Generated by Django 4.1.5 on 2023-01-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
