# Generated by Django 4.1.5 on 2023-01-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialPrice',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='price',
        ),
    ]
