# Generated by Django 4.1.5 on 2023-03-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_starttotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiameterSecondCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.diameters')),
            ],
            options={
                'verbose_name': 'Диаметр коронки 2 калькулятора',
                'verbose_name_plural': 'Диаметр коронки',
            },
        ),
    ]
