# Generated by Django 4.1.5 on 2023-01-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_materialprice_remove_materials_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diameters',
            old_name='materials',
            new_name='material',
        ),
    ]
