# Generated by Django 4.1.5 on 2023-03-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_diametersecondcalc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficients',
            name='start_total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.starttotal'),
        ),
    ]
