# Generated by Django 4.1.5 on 2023-03-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_coefficients_start_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coefficients',
            name='start_total',
        ),
        migrations.AddField(
            model_name='coefficients',
            name='Начальная цена',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.starttotal'),
        ),
    ]
