# Generated by Django 4.1.5 on 2023-03-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_coefficients_start_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coefficients',
            old_name='Начальная цена',
            new_name='start_total',
        ),
    ]
