# Generated by Django 4.2 on 2023-04-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_начальная цена_coefficients_start_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('order_list', models.JSONField(blank=True, null=True, verbose_name='Состав заказа')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterField(
            model_name='coefficients',
            name='start_total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.starttotal', verbose_name='Начальная цена'),
        ),
    ]
