# Generated by Django 4.2 on 2023-04-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_client_alter_coefficients_start_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заметка'),
        ),
    ]
