# Generated by Django 4.2 on 2023-04-13 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_client_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starttotal',
            options={'verbose_name': 'Начальные цены', 'verbose_name_plural': 'Начальные цены'},
        ),
        migrations.CreateModel(
            name='StartTotalWithoutCoef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.starttotal', verbose_name='Начальная цена')),
            ],
            options={
                'verbose_name': 'Начальная цена (без коэф)',
                'verbose_name_plural': 'Начальная цена (без коэф)',
            },
        ),
    ]
