# Generated by Django 4.1.5 on 2023-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_starttotal_options_starttotalwithoutcoef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order_list',
        ),
    ]
